export { default as AboutSection } from './AboutSection'
export { default as ContactSection } from './ContactSection'
export { default as EducationSection } from './EducationSection'
export { default as ExperienceSection } from './ExperienceSection'
export { default as HeroSection } from './HeroSection'
export { default as LearningSection } from './LearningSection'
export { default as SkillsSection } from './SkillsSection'
